### ISSUE TITLE
URL returned error 403

### ISSUE THREAD

**Issue by phr00t** [mamei16/LLM_Web_search#2]
I tried a silly question, which the model wanted to search... it looks like there was an error in the background which broke ooba text-ui :-(

![image](https://github.com/mamei16/LLM_Web_search/assets/5983470/c362589f-6c24-4e50-bdef-dd6844149dd0)

**Comment by phr00t** [comment]
Hmm... looks like a similar error happened earlier, but didn't break ooba webui. No results ever showed up and I had to click "Stop", but then nothing more could be generated. Maybe it got stuck looking for results when there were none?

**Comment by mamei16** [comment]
Hi! Thank you for taking the time to report this issue.

 I've pushed three fixes (9ffbf4a482615596c0bb54ded55c54cb0ca5e176, 2bd136c358e5f5e928d0260ad3cf7dd31edab35c and 6081ed58b00296726682a933b43fe2bc609d57b4) that should help. They contain the following changes:
1. Add HTTP request headers to reduces the amount of sites returning code 403
2. Do not crash the entire text-ui if no URL could be loaded (sorry about that)
3. Catch `requests.exceptions.ConnectionError`
4. Add a timeout, so that each site has max. 8 seconds to respond to a request

Let me know if these changes fixed your issue and feel free to open another issue if you encounter another bug.

**Comment by mamei16** [comment]
Also, thanks for the shout-out on LocalLLaMA 😃

**Comment by phr00t** [comment]
I'm not getting 403 errors anymore, but now I'm not getting any results. 

I opened another issue for that: https://github.com/mamei16/LLM_Web_search/issues/4
