### ISSUE TITLE
Support searx search engine on LLM_Web_search

### ISSUE THREAD

**Issue by OrcVole** [mamei16/LLM_Web_search#3]
searx is a meta search-engine that can be run locally and is a search tool which combines the results of several proprietary search engines like Google. It basically acts as a front-end for these anonymity destroying, corporate search engines.

Lets support searx on LLM_Web_search!

https://github.com/searx/searx
https://searx.thegpm.org/

**Comment by phr00t** [comment]
"Searx is no longer maintained. Thank you for your support and all your contributions."

**Comment by OrcVole** [comment]
Sorry, I forgot, the active fork is SearXNG:
https://github.com/searxng/searxng

Please consider supporting SearXNG.

**Comment by mamei16** [comment]
Hi, thanks for the suggestion! On first glance, SearXNG seems to be quite feature rich, so I think supporting it "fully" would too much of an undertaking right now. I could offer to add an UI element, where you can insert the URL of a SearXNG instance that can return JSON, which would then be used instead of DuckDuckGo. Everything SearXNG-related would have to be contained in the query. 
So, to use SearXNG to search Wikipedia for "Wau Holland" and specify a custom language (in this case french), the query would need to be:
```
 :fr !wp Wau Holland
``` 
Would you consider this enough support to be useful?

**Comment by OrcVole** [comment]
Yes, that would be enough and thank you. Could you include in the documentation the steps needed to set it to SearXNG, and then also a few examples of how to phrase a search eg one for wikipedia or rational wiki, one for e.g. latest football results, etc.

**Comment by mamei16** [comment]
Alright, I have added basic support for SearXNG (68a85f0eda681a5e890c0de36fcf5f14f88abb46) and updated the readme. However, phrasing the search query itself is not related to this extension, but is specific to SearXNG, so I can't help you with that. You can find some examples here: https://docs.searxng.org/user/search-syntax.html.
Let me know what you think!

**Comment by OrcVole** [comment]
Thank you very much!
